### ISSUE TITLE
Showing alt text resets zoom

### ISSUE THREAD

**Issue by kupiakos** [T-Rex96/Easy_xkcd#1]
I feel like this shouldn't happen.

**Comment by T-Rex96** [comment]
Seems to be an issue with the PhotoView library. I've tried saving the current zoom with getScale() and restoring it by calling setScale() right after the alt text gets visible, but for some reason it doesn't do anything

**Comment by T-Rex96** [comment]
There is now an alternative style for displaying the alt text that does not reset zoom anymore.
