### ISSUE TITLE
changing screen orientation resets color scheme

### ISSUE THREAD

**Issue by schachmat** [T-Rex96/Easy_xkcd#10]
When rotating the device to go into landscape mode, the ActionBar resets itself to the default gray/blue scheme.

**Comment by T-Rex96** [comment]
I'm not able to reproduce this on my device. Does this happen on a specific section of the app or just everywhere?

**Comment by schachmat** [comment]
I only tested in when viewing the latest comic. I am running the latest version 2.2 from F-Droid.

I can reproduce it with:
1. Start EasyXKCD.
2. Select a colorscheme, which is not the default one in the settings.
3. Press back and confirm to restart the app.
4. (App get's started to the last viewed comic) Turn the phone into landscape mode.

=> The toolbar changes color to the one from the default gray/blue scheme. Note, that the color of the bottom bar (back, home, apps) and the small system status bar (clock, notifications, …) still is the correct one chosen in step 2.

**Comment by T-Rex96** [comment]
Seems like the latest version 2.3 is not compiled by f-droid yet. It restarts automatically when changing theme and seems to also fix your bug, since I'm not able to reproduce it on this version

**Comment by schachmat** [comment]
You are right. Version 2.3.1 is available on F-Droid now and indeed the bug is fixed.
