### ISSUE TITLE
App opens, but crashes when a comic is selected

### ISSUE THREAD

**Issue by BlitzKraft** [T-Rex96/Easy_xkcd#100]
Version 5.3.2, Android 6.0.1 (Cyanogenmod nightly 20160830)

The app opens to the comics listing (comic overview). When a comic is selected, it crashes with the message "Unfortunately, Easy xkcd has stopped". 

I have reported it from the pop up error message. 

What-if opens to the listing, but when an article is selected, it shows just a plain white page.

**Comment by BlitzKraft** [comment]
Update: Well, must have been permissions issue. The app is using cached info, but the re-install didn't have enough permissions, but was trying to read the sdcard. 

Clearing the cache resolved the issue. Closing.

**Comment by T-Rex96** [comment]
Yeah that sometimes seems to happen when updating the OS, blame it on Google :D
