### ISSUE TITLE
Inefficient API is used

### ISSUE THREAD

**Issue by struggggle** [T-Rex96/Easy_xkcd#107]
Dear developers,

I found an inefficient API, setImageResource(), is used in Easy_xkcd. 

For setImageResource(), Google says this: 

https://developer.android.com/reference/android/widget/ImageView.html
" This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup. If that's a concern, consider using setImageDrawable(android.graphics.drawable.Drawable) or setImageBitmap(android.graphics.Bitmap) and BitmapFactory instead. "

I noticed that in the following code, setImageResource() is used:
de.tap.easy_xkcd.Activities.WhatIfActivity.java     performClick()   (lineNumber: 92 )
https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/Activities/WhatIfActivity.java

Do you think the use of setImageResource() will affect Easy_xkcd's performance? If yes, maybe we should move Bitmap reading and decoding to a background thread.

Thanks.

**Comment by T-Rex96** [comment]
This only happens for a single footnote in one What-If article, I think that's fine
