### ISSUE TITLE
Lime theme needs dark font in toolbar

### ISSUE THREAD

**Issue by schachmat** [T-Rex96/Easy_xkcd#11]
According to the [guidelines](https://www.google.com/design/spec/style/color.html#color-color-palette) the lime theme should use a dark font for better contrast. Technically the green theme is affected as well, but I think the contrast is fine there and having white font on the darker (700-tone) system bar and black font in the toolbar right below probably looks weird.

I looked at the source, but could not find an easy fix. The dark actionbar theme seems to be hardcoded in `tool_bar.xml` and the parents of the styles in `styles.xml` seem to be ignored, since only single values are extracted from those custom styles.

**Comment by T-Rex96** [comment]
Yeah it might be better to set the toolbar theme in styles.xml. Also, I'll have to include dark icons for the toolbar.

**Comment by T-Rex96** [comment]
I set the toolbar to a dark theme for testing purposes, don't you think this looks kinda weird too?

![device-2015-09-02-215708](https://cloud.githubusercontent.com/assets/13141438/9642617/78028b7c-51bd-11e5-93ff-d2ac4aa5a33c.png)

**Comment by schachmat** [comment]
Of course status bar (the topmost one with the clock) should use dark icons as well. Also the bottom bar. It only looks weird, because it's inconsistent.

**Comment by T-Rex96** [comment]
Sure, but is it even possible to change those?

**Comment by schachmat** [comment]
[Not yet](http://www.droid-life.com/2015/06/01/android-m-feature-light-colored-status-bar-could-mean-dark-notification-icons-in-apps/) it seems. Disabling the theme until then might be an idea, but otherwise, users can still just select another one. If you want, leave this report open as a reminder for when M hits, otherwise, close it.

**Comment by T-Rex96** [comment]
Yeah, after all theming is just based on personal preference, so let's close this
