### ISSUE TITLE
Xkcd 404 displays as 403

### ISSUE THREAD

**Issue by Caardvark** [T-Rex96/Easy_xkcd#113]
When one searches for comic 404, it shows the image of comic 403 instead.

**Comment by mueller-ma** [comment]
Cannot confirm. When I search for "404" I see an empty page.

**Comment by mueller-ma** [comment]
It seems to make a difference if you are using offline mode or not. In both cases [this](https://i.imgur.com/p0eKxKs.png) picture should be shown.
This should fix it for offline mode: https://github.com/mueller-ma/Easy_xkcd/commit/1637f6f7d56af5bad5ca6a050e256aa32a064fff

**Comment by T-Rex96** [comment]
Cool, wanna create a pull request?

**Comment by mueller-ma** [comment]
I'm not sure. I have changed the title of the 404 to "foo" for testing, but it still shown 404

**Comment by T-Rex96** [comment]
Fixed in the latest update.
