### ISSUE TITLE
Version 6.0 on Play Store?

### ISSUE THREAD

**Issue by CryptOwl** [T-Rex96/Easy_xkcd#115]
There's a version 6.0 of Easy xkcd on Play Store for quite a while now but it's neither on here nor on F-Droid.

What is going on?

**Comment by T-Rex96** [comment]
Forgot to push to github, sorry :/ 
The f-droid version should update in the next few days now

**Comment by Bubu** [comment]
I just added the latest version to f-droid again. Automatic updates were for some reason not enabled.

Should be picked up automatically form now on again!
