### ISSUE TITLE
App does not load comics on KitKat

### ISSUE THREAD

**Issue by bzobl** [T-Rex96/Easy_xkcd#117]
When launching easy_xkcd on my Asus Padfone 2 with 4.4.2 KitKat, the app does not show any comics, just a white screen and the share(?) symbol in the lower right corner. Clicking the icon displays a toast saying "No connection".
I can open the settings menu and enable "Launch to Overview Mode", which will then - on next launch - open the "Comics loading" fragment for a short time. Then it changes to the overview, displaying comics 1 to 1645. Clicking on any comic does yield the white screen again.

The bug is somewhat reproduceable using a Virtual Device, although the exception that is thrown differs on the Virtual Device. The root of the problem seems to be the same, though.

Error thrown on App Start in Virtual Device (4.4,2 KitKat):
`11-15 19:55:47.635 2341-2359/de.tap.easy_xkcd W/System.err: java.net.ConnectException: Failed to connect to xkcd.com/2a04:4e42:600::67:443
11-15 19:55:47.635 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
11-15 19:55:47.635 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
11-15 19:55:47.635 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
11-15 19:55:47.655 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
11-15 19:55:47.655 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-15 19:55:47.655 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-15 19:55:47.665 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
11-15 19:55:47.675 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:240)
11-15 19:55:47.675 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
11-15 19:55:47.675 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
11-15 19:55:47.675 2341-2359/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.utils.JsonParser.getJSONFromUrl(JsonParser.java:45)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.doInBackground(ComicBrowserFragment.java:151)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.doInBackground(ComicBrowserFragment.java:128)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-15 19:55:47.685 2341-2359/de.tap.easy_xkcd W/System.err:     at java.lang.Thread.run(Thread.java:841)`

Error thrown on Padfone 2 (4.4.2 KitKat):
`11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x613fb730: Failure in SSL library, usually a protocol error
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5d817d74:0x00000000)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:240)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.utils.JsonParser.getJSONFromUrl(JsonParser.java:45)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.doInBackground(ComicBrowserFragment.java:151)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.doInBackground(ComicBrowserFragment.java:128)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at java.lang.Thread.run(Thread.java:841)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: 	Suppressed: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x613fb730: Failure in SSL library, usually a protocol error
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5d817d74:0x00000000)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: 		... 22 more
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: 	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x613fb730: Failure in SSL library, usually a protocol error
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5d817d74:0x00000000)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-16 02:04:06.144 11157-11197/de.tap.easy_xkcd W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err: 		... 21 more
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x613fb730: Failure in SSL library, usually a protocol error
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x5d817d74:0x00000000)
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
11-16 02:04:06.154 11157-11197/de.tap.easy_xkcd W/System.err: 	... 21 more`

I'd appreciate any help on this problem,
thanks!

**Comment by T-Rex96** [comment]
Should be fixed in Version 6.0.2. I had to use http instead of https urls for KitKat and below. Let me know if the app now works for you!

**Comment by bzobl** [comment]
Great, works again for me.

Thanks!
