### ISSUE TITLE
'Earliest Unread Comic' button crashes app when all comics are read.

### ISSUE THREAD

**Issue by weaversam8** [T-Rex96/Easy_xkcd#125]
First off, great app! I use it every day!

So, I recently had a quest to ensure I haven't ever missed an XKCD comic. As part of that process, I repeatedly used the 'Earliest Unread Comic' button on the main list to page to any comic I hadn't read inside the app. This afternoon, I was sure to have read them all, and pressing the 'Earliest Unread Comic' button crashed the app.

I was only able to get part of the stacktrace, but hopefully this should help.
![stacktrace partial](https://user-images.githubusercontent.com/2546219/36447191-99d128d4-1651-11e8-8e08-063a54180e46.png)

I was looking through the code to see if I could fix it simply through a PR, but the bug seems to be actually bubbling up from the [Realm](https://realm.io/) Java library. Any ideas?

**Comment by T-Rex96** [comment]
Well that's weird, on my device this crash doesn't happen. The code catches `IndexOutOfBoundsException` which should also cover `ArrayIndexOutOfBoundsException`, so I'm not sure what's going on here. [This](https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/fragments/overview/OverviewBaseFragment.java#L176) is the place in the code where the exception should be caught, so maybe you can play around with that a bit and see if you can come up with a fix.

Sorry for taking so long to respond by the way.

**Comment by weaversam8** [comment]
You're right, it should be caught on [this line](https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/fragments/overview/OverviewBaseFragment.java#L186)... It doesn't make sense to me on why it wouldn't be caught there... maybe it's somewhere else...

**Comment by T-Rex96** [comment]
Does this still happen with the latest version?

**Comment by weaversam8** [comment]
I just tested it and now it does not crash the app. It silently fails and the app keeps working.

Sent from my Pixel 2

________________________________

**Comment by T-Rex96** [comment]
Great, that's what is supposed to happen
