### ISSUE TITLE
WebView Layout issue

### ISSUE THREAD

**Issue by tom-heimbrodt** [T-Rex96/Easy_xkcd#13]
There is still a layout issue in the WebView on my phone.
The text is incredibly huge with no possibility to zoom out (see screenshot).

I couldn't reproduce the issue on an emulator, it is only present on my device (Android 4.3) . . .

![device-2015-09-04-174758](https://cloud.githubusercontent.com/assets/8741140/9688206/0a1932ce-532e-11e5-9ad0-cdd4f812a8f9.png)

**Comment by tom-heimbrodt** [comment]
I figured out that setting the text zoom to something like 40% ends in an accaptable layout.
I simply added web.getSettings().setTextZoom(40); to the WebView init stuff.
The problem is that you can zoom in further if you want to, but unfortunately there is no possibility to zoom out.
Also this solution may break the layout on other devices . . .

**Comment by T-Rex96** [comment]
Does web.getSettings().setUseWideViewport(true) work for you?

**Comment by tom-heimbrodt** [comment]
No, the size is ok, but the text fills only a small part on the left side.

**Comment by T-Rex96** [comment]
That's normal behaviour when long formulas are displayed (happens on m.xkcd.com too). Still, on my Galaxy Nexus running Jelly Bean 4.3 web.getSettings().setUseWideViewPort(false) works fine, so this might be an issue with your device. I'll include an option in the app's settings to enable or disable WideViewPort.

**Comment by tom-heimbrodt** [comment]
Well, the internet browsers (Firefox and Chrome) work just fine.
Also the Dokumentation [here](http://developer.android.com/reference/android/webkit/WebSettings.html#setTextZoom(int)) states that the default text zoom is 100% and additionally setting it manually to 100% e. g. in the emulator, results in the same result as it is on my phone . . .
So [technically](http://www.xkcd.com/1475/), my phone is the one with the right implementation and manually setting the text zoom would be best practice.
I'd suggest adding an option to the app's settings, to choose the default text zoom.

**Comment by T-Rex96** [comment]
Yeah that would be a good solution.
