### ISSUE TITLE
Offline cache shows up in gallery applications

### ISSUE THREAD

**Issue by fynngodau** [T-Rex96/Easy_xkcd#131]
When saving comics or What if for offline use, the respective files show up in your typical gallery app (the one preinstalled on an average Android device, [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery), etc).

To fix this, all that has to be done is placing an empty `.nomedia` file in the folder that the image is stored in. This will cause the Android media scanner to ignore the files in that folder.

**Comment by T-Rex96** [comment]
The app would actually try to do that, but try only once, so if the user didn't give it the right permissions yet, the file wouldn't be created. This will be fixed in the upcoming release.
