### ISSUE TITLE
app crash when removed from Favorites 

### ISSUE THREAD

**Issue by kr-nahid** [T-Rex96/Easy_xkcd#134]
#### Expected behavior
this app shouldn't be crash while click on remove from favourite and rotated phone from portrait to landscape .

#### Actual behavior
when i  click on remove from favorites button and i rotated my phone from portrait to landscape after remove it occurs to crash .

#### How to reproduce
* download the app
* open it then select a comics to add favorites
* now go to **Favorites** and click on remove (love) icon to remove 
* rotated your phone from portrait to landscape when comics reomved
* note the bug

> Browser/App version: 6.0.4
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=3R2dN_UrNOQ

**Comment by T-Rex96** [comment]
Will be fixed in the upcoming release
