### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by krt16s** [T-Rex96/Easy_xkcd#15]
It would be great if you could tag releases (e.g. the commits bumping the versioncode) in a simple and consistent scheme (e.g. the plain versioname or versioncode) using `git tag TAGNAME` and then `git push --tags`. Readable tags are really helpful when checking out "known good" versions.

**Comment by T-Rex96** [comment]
Ok, I added the tag "release_x.y.z" for testing purposes, did I do it right?

**Comment by krt16s** [comment]
looks right to me. If you start the "real" tags, I can switch fdroids updatechecks to tags -- and even allow automatic app updates.

**Comment by T-Rex96** [comment]
Nice :)

**Comment by T-Rex96** [comment]
Ok, I just commited the latest version with the tag "release_2.7"!

**Comment by krt16s** [comment]
Thanks, I wont update to 2.7 and 2.7.1 manually, but will wait until tonight to check if it gets picked up by our auto-update. Closing.
