### ISSUE TITLE
No pictures in what-if

### ISSUE THREAD

**Issue by schachmat** [T-Rex96/Easy_xkcd#16]
I noticed, there are no pictures displayed for the what-ifs, just some tiny * or something like that which shows the alt-text when touched. Switching to offline mode for what-if and being on W-LAN instead of mobile internet did not change that behaviour, so I assume it is not related to those settings.

**Comment by T-Rex96** [comment]
Weird, got a screenshot?

**Comment by schachmat** [comment]
http://imgur.com/RSG5K7a

**Comment by T-Rex96** [comment]
Happens with every what-if article? Or just this specific one?

**Comment by schachmat** [comment]
With every one. I am currently on v3.1 from F-Droid on a Cyanogenmod 12.1 device without gapps.

**Comment by T-Rex96** [comment]
Could maybe be an issue with the missing gapps.. Clearing app data does not work either?

**Comment by schachmat** [comment]
Clearing app data solved it, thanks. I'll just assume it was caused due to some changes from an update. If it happens again, I will try to debug it a little more.
