### ISSUE TITLE
Overview mode

### ISSUE THREAD

**Issue by The0x539** [T-Rex96/Easy_xkcd#17]
So I personally have a small bit of a distaste for comic readers that show the comic like the site does, with just the comic and navigation back and forth. It'd be nice if part of the UI was a bit of an overview mode, a scrollable list of the comics. Maybe not a basic textual list, something visual like [this iOS app](https://i.imgur.com/CAbNFT2.png) could work nicely.

**Comment by T-Rex96** [comment]
Yeah it's one of the features I'm working on, the screenshot looks pretty nice!

**Comment by The0x539** [comment]
\o/

That'll definitely bring me all the way over from Blip.

**Comment by T-Rex96** [comment]
Finally added overview mode in the latest release. At the moment it's just a basic list, but I'll implement the image grid you suggested next :)

**Comment by The0x539** [comment]
Few thoughts on the current implementation:

* The way it currently works is kinda like "open this to select a comic". An alternate method, and one I *personally* would prefer, is something like the one used for the What If section, where you open a thing from the overview, and can subsequently return from said overview. Perhaps the latter UI could either be an alternative option or just replace the current version.
* When the image grid mode is done, if something along the lines of the bullet point above is used, it'd be cool if, a la Google Photos, one could pinch an already zoomed-out comic to return to the overview.
* I assume that if you intend on keeping+developing the list view alongside the image card, you also intend to reverse the direction, so new is on top.

**Comment by T-Rex96** [comment]
* Yep that is indeed the better way, I'll try to change it for the next update.

* That might be quite hard to implement, but I can try :)

* Yeah, new on top would make more sense now that you say it.

Note that I won't have time for developing this week (gotta write a physics lab report), so don't expect any big updates in the next few days

**Comment by T-Rex96** [comment]
Alright, I just pushed the update to Google Play and F-Droid which implements your first suggestion. 

I ran into some performance issues while trying to implement the image grid, though. Since the images are all different sizes, the grid constantly changed and scrolling became very laggy. I'll try to find a workaround, but for now I'll close this issue.

**Comment by The0x539** [comment]
[ccrama/Slide](http://github.com/ccrama/Slide) does a multiple-column cards thingy with variable card height, would its approach work?

**Comment by T-Rex96** [comment]
That could work, I'll take a look at the code when I have some time
