### ISSUE TITLE
Hangs at loading comics 

### ISSUE THREAD

**Issue by nutpantz** [T-Rex96/Easy_xkcd#18]
Ever since I see google play biking service permission added
Whenever I start easy xk it just hangs at loading comics if I have no internet

It's been a few updates since this started.

**Comment by T-Rex96** [comment]
I doubt there is a connection to the billing connection. So to be clear, this happens in offline mode when launching the app without an internet connection, right?

**Comment by T-Rex96** [comment]
I think I'll found the issue, in some case the progress dialog would not be dismissed. Let me know if that is fixed in the coming update.

**Comment by nutpantz** [comment]
Now the leading comics goes away quick but I'm left with a empty screen.
The Orange button is down on the bottom right, but no comic comes up.
Some times I'm connected to Wi-Fi but there is no internet access.
Other times the Wi-Fi is on but no connection
And yet other times no Wi-Fi on.

**Comment by ackzsel** [comment]
I have the same issues as nutpantz supposedly after the Google Billing permission. If the app crashes when working in foreground (which it does almost every session) the comic is replaced by a blank screen. The app also crashes a lot in the background, almost every time network connectivity changes state.

I'd like to add that this is a great and beautiful app and if these issues are resolved I think this is the best XKCD app out there!

Additional info:
Easy XKCD version 3.3
CyanogenMod 12.1 (lollipop 5.1.1)
No Google framework or apps installed

**Comment by T-Rex96** [comment]
Here's a version of the app that I removed the billing permission from:

https://www.dropbox.com/s/94rexzyu8933kte/3.3_no_billing.apk?dl=0

Could you try it out and see if it fixed anything?

**Comment by nutpantz** [comment]
Negative.  With testing however I noticed if works more often if I have Wi-Fi turned off as opposed to being connected to Wi-Fi that has no internet connection.
I tested this by using a firewall to stop easy xkcd access to internet and being connect to a local Wi-Fi network that is not connected to the internet.
When connected to the internet it always works.

Maybe it trying to connect every time to the internet and is hanging at that point.
I have it set to never auto update, but I think it's still trying.(If I'm reading my permission logs correctly)
Is there a manual update button option?

**Comment by T-Rex96** [comment]
Think I found the issue here, at the moment I call netInfo.isConnectedOrConnecting() to check if the device is online, when I should be calling netInfo.isConnected() instead. I guess i accidentally changed that in some update. Can you try it out? 

https://www.dropbox.com/s/kh6b5jb9u449vfj/3.3%20connection%20fix.apk?dl=0

**Comment by nutpantz** [comment]
Behaviour is still identical.
Maybe you need a quicker timeout in finding xkcd website with the fallback being offline mode.
If it sees the network it assumes there is internet and fails when it only a local network or behind firewall.
That is what it appears to me.  Might be part of Google's it your on the internet we want to know attitude.

**Comment by ackzsel** [comment]
For me reliability has improved. No crashes until now. I'll report back when I find something. Thanks for your quick actions.

**Comment by T-Rex96** [comment]
No new issues reported, so I'll close this for now.
