### ISSUE TITLE
Holding down finger after double-clicking to zoom causes the alt text to activate

### ISSUE THREAD

**Issue by kupiakos** [T-Rex96/Easy_xkcd#2]
I'm a big one-hand user of phones, and use one-finger zoom almost exclusively. I noticed that double clicking zooms in by some arbitrary amount. However, when using this method to zoom, if one continues to hold down their finger, the alt text will show on the bottom, the phone will vibrate, and the image will no longer be zoomed in. It's rather off-putting.

**Comment by T-Rex96** [comment]
Done! I've added a 500 ms delay for you to put up your finger. Also the zoom behavior is now:

1st double tap -> 0.5*maxZoom
2nd double tap -> maxZoom
3nd double tap -> zoom out
