### ISSUE TITLE
query on external storage

### ISSUE THREAD

**Issue by dizietsma** [T-Rex96/Easy_xkcd#21]
hi, i see you closed the issue on saving to external sdcard.  however on my moto g 4g (firstgen) the app (ver3.3) saves to the internal scdard storage and no to my micro sd external card.  the internal storage is at /storage/sdcard0 and the microsd card at /storage/sdcard1, 
am i missing something about getting comics to store on the microsd card?

diziet

**Comment by T-Rex96** [comment]
According to this stackoverflow question (http://stackoverflow.com/questions/5694933/find-an-external-sd-card-location) Environment.getExternalStorageState() doesn't seem to return the actual sd card path on some devices. Would you be ok with an option in the apps settings to set the exact path manually?

**Comment by dizietsma** [comment]
that would be cool, would the path be to the root of the microsd card or to the easyxkcd folder if i were to move the app to the sdcard?

diziet

**Comment by T-Rex96** [comment]
that could work too, feel free to try it out.

**Comment by T-Rex96** [comment]
The offline path can now be changed since the latest update, try it out!
