### ISSUE TITLE
Invisible actionbar when comic opened from search

### ISSUE THREAD

**Issue by vanitasvitae** [T-Rex96/Easy_xkcd#22]
Hi
When I sesrch for a comic, open it and want to share it, there is no actionbar. But the menu can still be opened.

**Comment by T-Rex96** [comment]
I already noticed that bug yesterday, will be fixed in the upcoming update.

**Comment by T-Rex96** [comment]
Just pushed the update to Google Play and F-Droid, so the bug should be fixed.
