### ISSUE TITLE
Commics appear twice

### ISSUE THREAD

**Issue by 42SK** [T-Rex96/Easy_xkcd#24]
Hello,
I've recently noticed that Easy xkcd sometimes displays the same comic twice when you swipe from one comic to the next. The title of the comic changes and the number in the toolbar increases, but the applications simply shows me the previous comic.

Here's an example (please excuse the size of the screenshots):

**This is comic 1306:**
![screenshot_2015-10-28-09-34-17](https://cloud.githubusercontent.com/assets/11149991/10784477/a7b7b97e-7d5e-11e5-9b29-0288fc136240.png)

**When I swipe to comic 1307, the application also displays comic 1306:**
![screenshot_2015-10-28-09-34-14](https://cloud.githubusercontent.com/assets/11149991/10784502/c53aa5b0-7d5e-11e5-9f83-e83ee3d5f48c.png)

I hope that you somehow manage to fix this.
I'd be delighted to provide any help if necessary.

**Comment by T-Rex96** [comment]
This is actually expected behavior, since comic 1037 was an april joke, it showed users different images based on their locations (see http://www.explainxkcd.com/wiki/index.php/1037:_Umwelt). Now, xkcd's json interface just gives you the image of the previous comic (http://xkcd.com/1037/info.0.json last line). 

Any other comics where this happens though?

**Comment by 42SK** [comment]
Thanks for your reply.
It's good to know that this is the intended behaviour.
I think I have noticed this at a few other comics too, but I don't remember where exactly.
Would it be possible to simply display a blank screen instead of the previous comic (like at comic 1416)?
It is a bit irritating when the title and the number in the toolbar are completely unrelated to the comic that is displayed.

**Comment by T-Rex96** [comment]
Would be possible, although for this comic I might just this image http://explainxkcd.com/wiki/images/f/ff/umwelt_the_void.jpg and add "interactive" to the title. Let me know if you find any other problematic comics though :)

**Comment by 42SK** [comment]
OK, Thanks! :-)

**Comment by tom-heimbrodt** [comment]
Additionally there is (or isn't) 404, where the last comic and title is shown.

**Comment by T-Rex96** [comment]
Yep, comic 404 does not exist, so I'll change the title to "404 - Not Found" and leave the image blank.

**Comment by 42SK** [comment]
I found another comic that is affected by this problem: 1350 is interactive and the json interface returns the image of the previous comic.

**Comment by T-Rex96** [comment]
Good catch, fixed: https://github.com/T-Rex96/Easy_xkcd/commit/cadc86812eb9cb1fea0762d5c57baf5eb575db75
