### ISSUE TITLE
App closes when phone turned in landscape mode

### ISSUE THREAD

**Issue by vanitasvitae** [T-Rex96/Easy_xkcd#25]
Hi
I just noticed that your app closes when I turn my phone sideways. There is no error message though.

**Comment by T-Rex96** [comment]
well that's pretty weird. Does it happen in every part of the app (e.g. the settings screen)

**Comment by vanitasvitae** [comment]
No, it only happens in the comic view activity (where you are when you just started the app)

**Comment by vanitasvitae** [comment]
Doesnt happen in your favourites.

**Comment by T-Rex96** [comment]
logcat output would be great, so that I can see what exactly caused the crash.

**Comment by vanitasvitae** [comment]
11-11 18:04:04.823 E/AndroidRuntime(20917): FATAL EXCEPTION: main
11-11 18:04:04.823 E/AndroidRuntime(20917): Process: de.tap.easy_xkcd, PID: 20917
11-11 18:04:04.823 E/AndroidRuntime(20917): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isDestroyed()' on a null object reference
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:133)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at com.bumptech.glide.Glide.with(Glide.java:644)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at de.tap.easy_xkcd.fragments.ComicBrowserFragment$ComicBrowserPagerAdapter$1loadComic.onPostExecute(ComicBrowserFragment.java:270)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at de.tap.easy_xkcd.fragments.ComicBrowserFragment$ComicBrowserPagerAdapter$1loadComic.onPostExecute(ComicBrowserFragment.java:251)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
11-11 18:04:04.823 E/AndroidRuntime(20917): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)

**Comment by T-Rex96** [comment]
Thanks, I'll look into it

**Comment by T-Rex96** [comment]
Does this version fix it?

https://www.dropbox.com/s/pj9pso3zju8j20q/3.4test.apk?dl=0

**Comment by vanitasvitae** [comment]
I will test it later.

**Comment by vanitasvitae** [comment]
Your link is dead. Did you already tested it yourself?

**Comment by T-Rex96** [comment]
Oops, that's my fault, however I already pushed the update to f-droid and google play now (should be live in a few hours), so you can just test it that way

**Comment by vanitasvitae** [comment]
The bug is fixed in the newest version. Thanks ;)
