### ISSUE TITLE
Cannot swipe when zoomed in

### ISSUE THREAD

**Issue by jimbo1qaz** [T-Rex96/Easy_xkcd#26]
I decided to try this app out again. I see that you still can't swipe to switch when zoomed in.

Suggestions to fix:
* Double-swipe to switch comics.
* Swipe action bar to switch comics.

Of course this should be user-configurable.

**Comment by T-Rex96** [comment]
Yeah sorry for not fixing this yet, I'll try to implement at least one of your suggestions.

**Comment by Dostoi** [comment]
Which one was implemented ? Cause I can't swipe with the last version when zooming

**Comment by jimbo1qaz** [comment]
"Always swipe when zoomed in". You need to enable in setting.

That's actually very troublesome. It would've been better to only switch
comics when the document, already at an edge, is dragged towards that edge.

**Comment by Dostoi** [comment]
Thanks for the answer.
Just tested it and I find it too sensitive too
