### ISSUE TITLE
Small comics are too big

### ISSUE THREAD

**Issue by jimbo1qaz** [T-Rex96/Easy_xkcd#27]
For example, 1602 takes up my entire phone display and cannot be zoomed out.

You could add a "maximum zoom"option or depend on screen DPI.

**Comment by T-Rex96** [comment]
I'm still not sure why one would want zoom out? You'd have to adjust the standard zoom based on dpi, screen size and image size which just seems to complicated at the moment.

**Comment by Foggalong** [comment]
[This is why.](https://cloud.githubusercontent.com/assets/5920259/11700233/8b90b06a-9ec0-11e5-82b3-2c8e3e8a7c6a.png) On larger screens the images are stretched to fill it making them look blury.

**Comment by T-Rex96** [comment]
Fixed in the latest release.
