### ISSUE TITLE
Large comics don't zoom in enough

### ISSUE THREAD

**Issue by danfiscus** [T-Rex96/Easy_xkcd#32]
Comics like #657 don't zoom in enough on my Galaxy S5 to be readable. (I don't remember if 657 specifically is like this, I just know 657 is a large comic. The problem is with the really large ones.)

**Comment by T-Rex96** [comment]
Make sure "large comics" is enabled in the app's settings.

Then go ahead and play aorund with the maximum scale a bit ;)

https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/fragments/ComicBrowserFragment.java#L396

https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/fragments/FavoritesFragment.java#L252

https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/java/de/tap/easy_xkcd/fragments/OfflineFragment.java#L585

**Comment by T-Rex96** [comment]
Just asking, did you try it out yet?

**Comment by danfiscus** [comment]
@T-Rex96 No, unfortunately I've been preoccupied with my broken laptop and I had to reset my phone, but I'll see what I can do today. I'll keep you updated.
(I've also been reading Thing Explainer when I should be working on school work... :)

**Comment by T-Rex96** [comment]
No problem, take your time ;)
