### ISSUE TITLE
Add Inverted Comics

### ISSUE THREAD

**Issue by BraydenDean** [T-Rex96/Easy_xkcd#33]
There should be an option to have a night/dark theme and have inverted comics (white on black instead of black on white). It shouldn't take much processing power and would add more options.

**Comment by T-Rex96** [comment]
The is already an option to invert colors. Or do you mean it should invert *just* white and black?

**Comment by BraydenDean** [comment]
No sorry I was behind on updates.

**Comment by T-Rex96** [comment]
Ok :)
