### ISSUE TITLE
Suggestion for overview mode

### ISSUE THREAD

**Issue by tom-heimbrodt** [T-Rex96/Easy_xkcd#34]
I don't know how far you are with implementing a better overview mode, but I just noticed there already is a pretty good list-based one: the search results.
If you search something, then search again (from the search activity), and finally clear your search you'll get a satisfying list of all comics out there.

![device-2015-12-06-181919](https://cloud.githubusercontent.com/assets/8741140/11614552/494ff2be-9c46-11e5-8ded-eaf93c24c2f1.png)

Wouldn't it be easier to improve this one (e.g. reverse it, so the newest comic is on top, and add a scroll bar) than completely writing a  new one? As an extra, we'd have a consistent design in the whole app.
Of course, there might be a grid-based one too, and the user can select which is shown with an entry in the settings.

**Comment by T-Rex96** [comment]
That could work too! Unfortunately RecyclerView doesn't support fast scroll bars like ListView does, so I'll have to look for a library that implements it.
