### ISSUE TITLE
Comic 104 is upside down

### ISSUE THREAD

**Issue by 42SK** [T-Rex96/Easy_xkcd#39]
The [JPEG file](http://imgs.xkcd.com/comics/find_you.jpg) of comic 104 seems to be upside down.
Perhaps someone can find a way to turn this image before it is displayed.

**Comment by T-Rex96** [comment]
Also, comic 76 and 80 are sideways. I think the easier solution would be to reupload those on imgur and add it to the Comic class. I'll take care of that.
