### ISSUE TITLE
Show the new comic available button longer

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#41]
The button that tells that there is a new comic doesn't stay long enough. Could it stays a couple of seconds longer ?

**Comment by T-Rex96** [comment]
Currently the Snackbar (the button)  uses Snackbar.LENGTH_LONG which is 2750ms, but I think something like 4000ms would be fine. You don't want it to stay on screen to long, since most users don't know that it can be swiped away.

**Comment by Dostoi** [comment]
Yes, just a bit longer is fine and I can understand that some will find it bothersome

**Comment by T-Rex96** [comment]
Ok. After all, you can always select "Latest Comic" from the overflow menu when you missed the Snackbar.

**Comment by Dostoi** [comment]
Thanks !
