### ISSUE TITLE
Add a bookmark option

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#42]
Is it possible to have a bookmark option ?
Right now, I'm reading all the xkcd comics starting from the most recent one but when there is a new one and I go to see it, I have to search for the one I was reading before.
Having an option as save current comic as bookmark and go to bookmark to easily go to the saved one would be nice.

Thanks in advance :)

**Comment by T-Rex96** [comment]
That's a really cool idea! I'm going to ski holidays for one week tomorrow, so I'll have only have time to implement this when I'm back.

**Comment by Dostoi** [comment]
Don't worry, no need to rush it. Enjoy your holidays :)
