### ISSUE TITLE
Issue with the comic list when going back from a comic

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#43]
When going back from a comic to the comic list, the app doesn't show the list near the comic I was reading (for example 1518) but close to the first one (it's around 100).
So I have to go back to the top and search for my comic.
But once I've done that and if I go back again, it shows the right place in the list.
But if I close the app(not just quitting it), and do this again, the issue is here again.

Not sure if I'm clear enough ^^

**Comment by T-Rex96** [comment]
I'll look into that!

**Comment by Dostoi** [comment]
And it seems the more I go down in the seen comics(1504), the more it goes up when I go back to the comic list (114 now).

**Comment by Dostoi** [comment]
After some test, it seems to be keeping the position but in the wrong order. I'm at the 120 comics from the top and it put me at the 120 comics from the beginning when I go back to the list view

**Comment by T-Rex96** [comment]
Thanks for your detailed description, should be fixed in the next update!

**Comment by Dostoi** [comment]
No problem, happy to help
