### ISSUE TITLE
Add to favorites doesn't change if already favorite

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#45]
When pressing the add to favorites button to a comic which isn't a favorite, the phrase doesn't switch to delete from favorites (or whatever it should be). It still shows add to favorites and pressing it again delete the comic from favorites.

With version 3.8.3

**Comment by T-Rex96** [comment]
I'll fix that when I get home on Saturday :)

**Comment by Dostoi** [comment]
Ok perfect :)
