### ISSUE TITLE
No remove from favorite in the favorite menu

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#48]
When in the favorite menu, there's no option to remove the comic which is displayed, only one to clear all favorites

**Comment by T-Rex96** [comment]
Screenshot would be helpful here

**Comment by Dostoi** [comment]
![screenshot_2016-01-05-07-02-58](https://cloud.githubusercontent.com/assets/7694864/12108656/7c6e906a-b37a-11e5-832a-dcc77392f810.png)

**Comment by T-Rex96** [comment]
Tapping the heart icon will remove the comic from favorites ;)

**Comment by Dostoi** [comment]
Ok my bad ^^
