### ISSUE TITLE
Add to favorites option in the comics list

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#49]
When you're in the comic list, there's an option "add to favorites" which doesn't add to favorites but switch to a favorite list. The option is present here too and it switch back to the normal comic list.

**Comment by T-Rex96** [comment]
Oh yeah soryy, forgot about that. Usually the Favorite Button is always displayed as an icon, so it seems like your screen is very small

**Comment by Dostoi** [comment]
It's 4.3 ^^
