### ISSUE TITLE
Enhancement - Setting to force auto-landscape

### ISSUE THREAD

**Issue by luigibai** [T-Rex96/Easy_xkcd#5]
I prefer to view the images in landscape mode, so it would be helpful to have a Settiing that forces the device into landscape mode when in the Easy XKCD app.

Thanks!

**Comment by T-Rex96** [comment]
I'll look into it! Got a physics exam coming up on friday thouh, so you shouldn't expect an update before saturday

**Comment by luigibai** [comment]
Best of luck on the exam!

**Comment by T-Rex96** [comment]
Thanks :)

**Comment by luigibai** [comment]
You might take a look at [SimpleDilbert](https://github.com/smarek/Simple-Dilbert/search?utf8=%E2%9C%93&q=landscape) for inspiration.

**Comment by T-Rex96** [comment]
nice!

**Comment by T-Rex96** [comment]
Done! Doing some code cleanup atm, so it might take a day or two until it's live in the Play Store.

**Comment by luigibai** [comment]
Thanks! I'll be looking for it on f-droid.org.
