### ISSUE TITLE
A Changelog would be nice!

### ISSUE THREAD

**Issue by noisnogit** [T-Rex96/Easy_xkcd#50]
Could you make a simple Changelog just to keep us updated about the changes from a release to another?

Thanks

**Comment by T-Rex96** [comment]
There actually is a changelog in the app's licenses screen (https://github.com/T-Rex96/Easy_xkcd/blob/master/app/src/main/res/raw/licenses.html), I forgot to update it for some time though. I'll add it to the README.md

**Comment by noisnogit** [comment]
Oh, thanks for your prompt response. But you could put a Changelog.md in master so it would be more easily accessible :) And also link it to F-droid...

**Comment by noisnogit** [comment]
Thank you :D
