### ISSUE TITLE
Issue with alt text

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#53]
I've found others so maybe keeping this issue open for some time in case I found other again to avoid creating a lot of issue just for that ?

https://xkcd.com/1234/ the "you're" isn't displayed properly it show "youâ re"

https://xkcd.com/1147/ the "é" of "Pokémon" isn't displayed properly too

**Comment by T-Rex96** [comment]
I found a fix for all the alt text issues a few days ago, but haven't pushed a new update yet.

**Comment by Dostoi** [comment]
Ho ok great then :)
