### ISSUE TITLE
Comic 1227 isn't displayed

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#55]
I've got the alt text and title but the comic isn't displayed
https://xkcd.com/1227/

**Comment by T-Rex96** [comment]
#1227 has a very large image. For each Android device there seems to be a maximum size for images (4096x4096 on my Nexus 7 and Nexus 5x), this may be a smaller limit on your device. If you take a look at the logcat output you'll probably see an OutOfMemoryError when trying to load the comic.

**Comment by Dostoi** [comment]
Thanks for the explanation, closing it then
