### ISSUE TITLE
Display .gif images properly

### ISSUE THREAD

**Issue by 42SK** [T-Rex96/Easy_xkcd#61]
The comic browser fails to display the animations of comics that are .gif images (such as [961](https://xkcd.com/961/)).
It would be nice if we could implement proper support for .gif files.

**Comment by T-Rex96** [comment]
As far as I know the only .gif comics are 961 and 1116, so the easiest way to fix this would be to include them in the apk (size is only ~90 Kilobytes) and then let Glide do the remaining work (by checking if the comicnumber is 1116 or 961 in the ComicAdapter Class)

**Comment by PeterHindes** [comment]
This solution is pretty bad. How hard would it be to actually load the gifs?
