### ISSUE TITLE
Don't import de.tap.easy_xkcd.database.DatabaseManager

### ISSUE THREAD

**Issue by krt16s** [T-Rex96/Easy_xkcd#69]
You import  `de.tap.easy_xkcd.database.DatabaseManager` but it is not included included in this repository. However, it doesnt look it's actually ever used, so it might be a left over.

**Comment by T-Rex96** [comment]
It's actually a new class I'm working on at the moment, but haven't comitted to Git yet. That import statement is just accidentally included in the last release, so this will be fixed in the next release.
