### ISSUE TITLE
Having a way to now about new features

### ISSUE THREAD

**Issue by Dostoi** [T-Rex96/Easy_xkcd#72]
Is it possible to have a pop up message when first launching the app after an upgrade to now that there's a new feature available in the app ?
Or a changelog. Whatever you find the least bothersome :)

**Comment by T-Rex96** [comment]
Changelog is here: https://github.com/T-Rex96/Easy_xkcd/blob/master/CHANGELOG.md

**Comment by Dostoi** [comment]
Ok no problem, closing it then
