### ISSUE TITLE
Feature request: Show article number in what-if 

### ISSUE THREAD

**Issue by BlitzKraft** [T-Rex96/Easy_xkcd#75]
In the title bar on what-if, there is currently no indication of the article number. But the comic view does. 

Having it makes it easier to look up the article later.

**Comment by T-Rex96** [comment]
I'm on it!

**Comment by T-Rex96** [comment]
Most of the time it wouldn't fit into the title bar, so I added the numbers to the overview instead, hope that works for you too.

![screenshot_20160404-103024](https://cloud.githubusercontent.com/assets/13141438/14242222/5c09aa4a-fa50-11e5-89a0-5c4865f43385.png)

**Comment by BlitzKraft** [comment]
That does the job! I just wanted the reference whenever I stashed something to read later.

It's easier for me to type the url and number than google the title.
