### ISSUE TITLE
Alternate card style for overview

### ISSUE THREAD

**Issue by The0x539** [T-Rex96/Easy_xkcd#76]
https://i.imgur.com/dDWtf4M.png

Something like the image above, _maybe_ with only a single column.

**Comment by T-Rex96** [comment]
Like this?

It works fine in offline mode, but scrolling up is a bit choppy in online mode, since we do not know the size of the images before downloading them. Not a dealbreaker though.

![](https://dl2.pushbulletusercontent.com/6qPyXV46bETRcmmYC2i1SgNRtdje5b8A/Screenshot_20160407-104438.png)

**Comment by The0x539** [comment]
Feel like the text should be darker, but yeah.

**Comment by T-Rex96** [comment]
Should be same color that's used for the small cards. It might seem less dark because of the smaller text size I guess

**Comment by T-Rex96** [comment]
It's included in the latest release, so let me know how it works for you!

**Comment by The0x539** [comment]
Seems to work, but Garden gets like a quantum thumbnail or something. Changes every time I scroll to it, rather amusing but doubt it's intended.

**Comment by T-Rex96** [comment]
Does it also move a around a bit?

**Comment by The0x539** [comment]
Yes.

**Comment by T-Rex96** [comment]
Yeah this seems to be a bug with Android's StaggeredGridLayoutManager

**Comment by The0x539** [comment]
Give it a dummy thumbnail of an empty garden?

**Comment by T-Rex96** [comment]
Sry, missed you reply for some reason. Now that there are some newer comics, is the bug still there?

**Comment by The0x539** [comment]
Yes, it is.

**Comment by T-Rex96** [comment]
Same comic? Online or offline mode?

**Comment by The0x539** [comment]
Offline, still just Garden.

**Comment by T-Rex96** [comment]
Guess that's because it was downloaded to your device before i put in the dummy thumbnail in the next update, so that's why the app is confused. You can try to put you own empty-garden-image named 1663.png into your easyxkcd folder

**Comment by The0x539** [comment]
Remaining problems with implication have since largely become irrelevant
