### ISSUE TITLE
Unicode/UTF-8 support missing.

### ISSUE THREAD

**Issue by BlitzKraft** [T-Rex96/Easy_xkcd#77]
This is a suggestion/enhancement. 
![2016-04-13-174241_862x737_scrot](https://cloud.githubusercontent.com/assets/6516167/14511747/48e2ba78-019f-11e6-8092-b89a3f928766.png)

The character missing in the word centrifuetal is "ᵫ" (U+1D6B). 

I haven't seen many  comics/what-ifs with too much unicode, but would be nice if done.

**Comment by T-Rex96** [comment]
Right, which what-if is this? Unicode in comics already works btw.

**Comment by BlitzKraft** [comment]
what-if.xkcd.com/116 - No rules NASCAR

**Comment by T-Rex96** [comment]
![]
(https://dl2.pushbulletusercontent.com/Y8L9btAmqRCv7w9817XylJCyml8LS65e/Screenshot_20160414-105257.png)

Seems to work on my Nexus 5X. What's you device/android version? Is offline mode enabled?

**Comment by BlitzKraft** [comment]
Probably just my device then. It's 4.4.2 samsung galaxy active i537.

**Comment by T-Rex96** [comment]
Yeah Samsung devices can be weird sometimes, so let's close this for now.
