### ISSUE TITLE
Using HTTPS

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#80]
At least an option would be nice to use [HTTPS](https://xkcd.com/). Please also use HTTPS when sharing a link...

**Comment by T-Rex96** [comment]
Will do :)

**Comment by mueller-ma** [comment]
@T-Rex96 Please reopen. I have seen, that some workarounds use explainxkcd.com which doesn't offer https. It might be possible to upload them here in this repo to get them in https.
