### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#81]
It would be awesome to have a wdget with xkcd comics.

Please let us choose between "daily comic" (the most up-to-date comic) and "random comic" (where a random comic is chosen). So these 2 widgets would be nice...

**Comment by T-Rex96** [comment]
I'll se if I can work something out

**Comment by T-Rex96** [comment]
Just wanted to let you know that I'm still working on it. I don't really have much time for coding atm, but the groundwork for the widget is laid. I'll have to work out design/layout though.

**Comment by T-Rex96** [comment]
Check it out in the latest release :)

**Comment by rugk** [comment]
Awesome! It works...
