### ISSUE TITLE
Night mode should only invert black/white pictures

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#82]
E.g. this picture is also inverted which does not look good: https://xkcd.com/766

**Comment by T-Rex96** [comment]
Explainxkcd seems to have a list of all colored comics: https://www.explainxkcd.com/wiki/index.php/Category:Comics_with_color

I'll try to include it!

**Comment by rugk** [comment]
Can't you somehow analyze the picture itself? Color depth?
Because there also may be future colored comics and you won't always want to publish an update to include it in a the exclude list.

**Comment by T-Rex96** [comment]
Might be possible to, but that could cause problems with comics like http://www.xkcd.com/136/ . It _does_ have some color, but it should still be inverted

**Comment by schachmat** [comment]
How about using color palette analysis and the list combined? It would always be correct for the old comics then and for new ones it will at least "probably" be correct.

**Comment by T-Rex96** [comment]
Yeah that's a good compromise

**Comment by The0x539** [comment]
I've seen things that invert only the lightness of the image, and not the hue. Would that be at all possible?

**Comment by T-Rex96** [comment]
Ok, so the Android Support Library has a pretty cool method palette.getVibrantSwatch() which returns null if the bitmap contains almost no colors. Seems to work pretty well for our xkcd images!

**Comment by schachmat** [comment]
> I've seen things that invert only the lightness of the image, and not the hue. Would that be at all possible?

That only works for images where colors are just used to highlight specific image elements. For photographic like pictures it looks quite weird (My pdf viewer has this brightness only inversion enabled by default), for example comic 766 mentioned above. Fortunately those are just a few of all the xkcd comics affected by that problem, so a blacklist for already published comics and the getVibrantSwatch heuristic for detecting not yet known colored comics and then apply the brightness only inversion seem to be a good compromise.

**Comment by The0x539** [comment]
So getVibrantSwatch returns null for, say, 446?

**Comment by T-Rex96** [comment]
Nope.
