### ISSUE TITLE
Explain xkcd supports HTTPS

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#84]
Because they are using Cloudflare.

https://explainxkcd.com/

So what about changing the links?

**Comment by T-Rex96** [comment]
Sure, looks like I missed that one

**Comment by rugk** [comment]
Yeah, I also created a [HTTPS Everywhere ruleset](https://github.com/EFForg/https-everywhere/pull/4724).

**Comment by rugk** [comment]
Okay, probably better not change it: [You cannot sign up via HTTPS there](https://github.com/EFForg/https-everywhere/issues/4578).
Therefore I am closing this issue. The authors of the wiki have to fix their site first. If anyone can convince them to fix it, please do.
