### ISSUE TITLE
only 1655 comics viewable

### ISSUE THREAD

**Issue by stop5** [T-Rex96/Easy_xkcd#85]
I can only access Comic 1-1655, as well as on the latest.
i have the version 5.2, I have activated th Offline mode for the comics and for What-If, also the large image setting.

**Comment by T-Rex96** [comment]
Ave you tried "repair offline" (settings->advanced)?

**Comment by stop5** [comment]
I have done this, but it didn't work.

**Comment by T-Rex96** [comment]
Weird, could you provide some screenshots?

**Comment by stop5** [comment]
[Screencast.mp4.zip](https://github.com/T-Rex96/Easy_xkcd/files/264495/Screencast.mp4.zip)
i have made an video from the bug, this should show you what I mean. Its in the zipfile

**Comment by T-Rex96** [comment]
Oh ok, didn't realize you're talking about overview mode. Are you sure the "Hide read"  ("Versteckene gelesene") option is not checked?

**Comment by stop5** [comment]
Hide read is not checked and if i check it it only show me comic 0, because i have read all. I have made the video only of this view, because the two others have also this bug

**Comment by T-Rex96** [comment]
What happens when you select "mark all as read" ?

**Comment by stop5** [comment]
it makes no difference if they are marked as read or not.

**Comment by T-Rex96** [comment]
I'm sorry, I don't really know what's causing the bug then. Deleting app data may work

**Comment by stop5** [comment]
now it works. Thank for the help.
