### ISSUE TITLE
Overview in favoured comics

### ISSUE THREAD

**Issue by rugk** [T-Rex96/Easy_xkcd#86]
The search menu already has a kind of overview, but it would be nice if the favourites many would also have such a menu, so one can have a look at all favoured comics at a glance.

A grid view would possibly also suitable here.

**Comment by T-Rex96** [comment]
In normal overview mode (all comics) just tap the "heart"-icon ;)

**Comment by rugk** [comment]
Ah, where?
Tipping the heard icon adds or deletes the picture from the favourites.

**Comment by T-Rex96** [comment]
[(https://dl2.pushbulletusercontent.com/xqtfH8J3gw9TglS1bPJaswSHmy5JHsfS/Screenshot_20160515-180425.png)

That one ;)

**Comment by rugk** [comment]
Ahh, I finally got it.

I have to be in the "Comics" section and press back if I'm already viewing a comic. There I can click on the heart...

**Comment by rugk** [comment]
The thing that I could not view an overview over my favoured comics in the "favorites" tab, but in the "comics" tab, surprised me...

Maybe you can consider changing this a bit...
I hope I was a good sample for testing UX... :laughing:

**Comment by T-Rex96** [comment]
Just finished implementing it :)

**Comment by rugk** [comment]
I think this is still the same. (At least in the latest FDroid release)
Especially there is a functionality problem: when you have no internet connection you cannot see an overview of your favored comics, because to do this you have to switch to the "comic browser" which shows an error when there is no internet connection.
