### ISSUE TITLE
Screen clears after toggling night mode or changing the phone orientation

### ISSUE THREAD

**Issue by schachmat** [T-Rex96/Easy_xkcd#87]
Nothing is displayed in the app anymore, I could only 'fix' it by killing and restarting the App.

If you need more info, let me know.

**Comment by T-Rex96** [comment]
Yeah screenshots or even a video would be helpful

**Comment by schachmat** [comment]
[Screenshot](http://s33.postimg.org/6gwrrawov/Screenshot_20160527_152514.png)

**Comment by T-Rex96** [comment]
Could be, but I can't say for sure. Maybe a logcat output would help to see what's actually going on

**Comment by schachmat** [comment]
I captured a [video](http://fs.tum.de/~teichm/Media/easy_xkcd_bug.mp4) of the bug.

logcat (main):

    05-27 20:36:36.309  1012  1768 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.tap.easy_xkcd/.Activities.MainActivity (has extras)} from uid 10019 on display 0
    05-27 20:36:36.337  1012  4440 I ActivityManager: Start proc 22356:de.tap.easy_xkcd/u0a100 for activity de.tap.easy_xkcd/.Activities.MainActivity
    05-27 20:36:36.723 22356 22375 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (Ia6c73e7530)
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: Build Date: 11/17/15 Tue
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: Local Branch: mybranch16463693
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.4
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: Local Patches: NONE
    05-27 20:36:36.774 22356 22375 I Adreno-EGL: Reconstruct Branch: NOTHING
    05-27 20:36:36.780 22356 22375 I OpenGLRenderer: Initialized EGL, version 1.4
    05-27 20:36:36.826   274   932 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
    05-27 20:36:36.826   274   932 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
    05-27 20:36:36.892  1012  1057 I ActivityManager: Displayed de.tap.easy_xkcd/.Activities.MainActivity: +567ms
    05-27 20:36:38.379  1012  1691 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
    05-27 20:36:38.380  1012  1691 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 100] to 59
    05-27 20:36:39.006  1012  1313 I InputReader: Reconfiguring input devices.  changes=0x00000004
    05-27 20:36:39.006  1012  1313 I InputReader: Device reconfigured: id=2, name='touch_dev', size 1440x2560, orientation 1, mode 1, display id 0
    05-27 20:36:39.008  1012  1053 I ActivityManager: Config changes=480 {1.0 262mcc2mnc en_US ldltr sw411dp w683dp h387dp 560dpi nrml land finger -keyb/v/h -nav/h s.39 themeResource=null}
    05-27 20:36:39.173  1012  1057 I WindowManager: Screen frozen for +195ms due to Window{ad39243 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}
    05-27 20:36:40.584  1012  1263 V sensors_hal_Light: processReportInd: 30000 3.000000
    05-27 20:36:40.599  1012  1300 D sensors_hal_Ctx: poll:polldata:1, sensor:0, type:1, x:5.736694 y:1.072357 z:7.063751
    05-27 20:36:40.664  1012  1300 D sensors_hal_Ctx: poll:polldata:1, sensor:0, type:1, x:5.989014 y:0.714111 z:7.864746
    05-27 20:36:40.800  1012  1049 I ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10016 on display 0
    05-27 20:36:40.833  1863  1863 I art     : Starting a blocking GC Explicit
    05-27 20:36:40.874  1863  1863 I art     : Explicit concurrent mark sweep GC freed 977(50KB) AllocSpace objects, 3(820KB) LOS objects, 38% free, 25MB/41MB, paused 446us total 40.812ms
    05-27 20:36:40.879  1863  1863 I art     : Starting a blocking GC Explicit
    05-27 20:36:40.904  1863  1863 I art     : Explicit concurrent mark sweep GC freed 20(720B) AllocSpace objects, 0(0B) LOS objects, 38% free, 25MB/41MB, paused 443us total 23.977ms
    05-27 20:36:40.904  1863  1863 I art     : Starting a blocking GC Explicit
    05-27 20:36:40.924  1863  1863 I art     : Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 38% free, 25MB/41MB, paused 689us total 19.956ms
    05-27 20:36:41.313  1012  1689 D WifiStateMachine: starting scan for "Csatlakozik"-WPA_PSK with 2462
    05-27 20:36:41.400  1012  1691 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
    05-27 20:36:41.400  1012  1691 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 100] to 56
    05-27 20:36:41.840  1012  3398 D NetlinkSocketObserver: NeighborEvent{elapsedMs=21655909, 192.168.178.1, [9CC7A6A54B66], RTM_NEWNEIGH, NUD_REACHABLE}
    05-27 20:36:42.263  1012  1767 I ActivityManager: Killing 22356:de.tap.easy_xkcd/u0a100 (adj 9): remove task
    05-27 20:36:42.291  1012  4440 I WindowState: WIN DEATH: Window{ad39243 u0 de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity}

logcat (events):

    05-27 20:36:36.317  1012  1768 I am_create_activity: [0,191652633,30,de.tap.easy_xkcd/.Activities.MainActivity,android.intent.action.MAIN,NULL,NULL,270532608]
    05-27 20:36:36.318  1012  1768 I wm_task_created: [30,16]
    05-27 20:36:36.318  1012  1768 I wm_task_moved: [30,1,1]
    05-27 20:36:36.318  1012  1768 I am_pause_activity: [0,106486264,com.cyanogenmod.trebuchet/com.android.launcher3.Launcher]
    05-27 20:36:36.320  1012  1768 I am_home_stack_moved: [0,0,16,16,startedActivity setFocusedActivity]
    05-27 20:36:36.320  1012  1768 I wm_task_moved: [30,1,1]
    05-27 20:36:36.323  1012  1768 I am_focused_activity: [0,de.tap.easy_xkcd/.Activities.MainActivity]
    05-27 20:36:36.324  2516  2516 I am_on_paused_called: [0,com.android.launcher3.Launcher]
    05-27 20:36:36.337  1012  4440 I am_proc_start: [0,22356,10100,de.tap.easy_xkcd,activity,de.tap.easy_xkcd/.Activities.MainActivity]
    05-27 20:36:36.367  1012  9080 I am_proc_bound: [0,22356,de.tap.easy_xkcd]
    05-27 20:36:36.368  1012  9080 I am_restart_activity: [0,191652633,30,de.tap.easy_xkcd/.Activities.MainActivity]
    05-27 20:36:36.752 22356 22356 I am_on_resume_called: [0,de.tap.easy_xkcd.Activities.MainActivity]
    05-27 20:36:36.755   266   266 I sf_frame_dur: [com.cyanogenmod.trebuchet/com.android.launcher3.Launcher,53,2,1,1,0,0,3]
    05-27 20:36:36.892  1012  1057 I am_activity_launch_time: [0,191652633,de.tap.easy_xkcd/.Activities.MainActivity,567,567]
    05-27 20:36:37.138   266   266 I sf_frame_dur: [Loading Comics…,1,1,0,0,0,0,0]
    05-27 20:36:39.007  1012  1053 I configuration_changed: 1152
    05-27 20:36:39.017  1012  1053 I am_relaunch_resume_activity: [0,191652633,30,de.tap.easy_xkcd/.Activities.MainActivity]
    05-27 20:36:39.021 22356 22356 I am_on_paused_called: [0,de.tap.easy_xkcd.Activities.MainActivity]
    05-27 20:36:39.072   266   266 I sf_frame_dur: [de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity,35,1,0,0,0,0,0]
    05-27 20:36:39.107 22356 22356 I am_on_resume_called: [0,de.tap.easy_xkcd.Activities.MainActivity]
    05-27 20:36:40.801  1012  1049 I am_home_stack_moved: [0,1,0,0,bringingFoundTaskToFront setFocusedActivity]
    05-27 20:36:40.801  1012  1049 I wm_task_moved: [5,1,1]
    05-27 20:36:40.802  1012  1049 I am_focused_activity: [0,com.android.systemui/.recents.RecentsActivity]
    05-27 20:36:40.818  1012  1049 I am_pause_activity: [0,191652633,de.tap.easy_xkcd/.Activities.MainActivity]
    05-27 20:36:40.819 22356 22356 I am_on_paused_called: [0,de.tap.easy_xkcd.Activities.MainActivity]
    05-27 20:36:40.824  1012  1049 I am_relaunch_resume_activity: [0,251903361,5,com.android.systemui/.recents.RecentsActivity]
    05-27 20:36:40.826  1012  1049 I am_task_to_front: [0,5]
    05-27 20:36:40.826  1012  1049 I am_new_intent: [0,194187167,5,com.android.systemui/.recents.RecentsActivity,com.android.systemui.recents.SHOW_RECENTS,NULL,NULL,281034752]
    05-27 20:36:40.964  1863  1863 I sysui_view_visibility: [224,100]
    05-27 20:36:40.968  1863  1863 I sysui_count: [overview_trigger_nav_btn,1]
    05-27 20:36:40.968  1863  1863 I sysui_count: [overview_source_app,1]
    05-27 20:36:40.968  1863  1863 I sysui_histogram: [overview_source_app_index,0]
    05-27 20:36:40.968  1863  1863 I sysui_histogram: [overview_task_count,2]
    05-27 20:36:40.968  1863  1863 I am_on_resume_called: [0,com.android.systemui.recents.RecentsActivity]
    05-27 20:36:41.292  1863  1863 I sysui_recents_event: 1
    05-27 20:36:41.658   266   266 I sf_frame_dur: [de.tap.easy_xkcd/de.tap.easy_xkcd.Activities.MainActivity,7,4,0,0,0,0,0]
    05-27 20:36:42.258  1863  1863 I sysui_histogram: [overview_task_dismissed_source,1]
    05-27 20:36:42.259  1012  1767 I am_finish_activity: [0,191652633,30,de.tap.easy_xkcd/.Activities.MainActivity,clear-task-index]
    05-27 20:36:42.259  1012  1767 I am_destroy_activity: [0,191652633,30,de.tap.easy_xkcd/.Activities.MainActivity,finish-imm]
    05-27 20:36:42.263  1012  1767 I am_kill : [0,22356,de.tap.easy_xkcd,9,remove task]
    05-27 20:36:42.303  1012  1834 I am_proc_died: [0,22356,de.tap.easy_xkcd]

**Comment by T-Rex96** [comment]
Don't really see anything wrong there, no error message. weird...

**Comment by T-Rex96** [comment]
Update: I found the bug, there will be an update as soon as possible!

**Comment by schachmat** [comment]
Fixed in 5.2.2. Thanks!
