### ISSUE TITLE
what if overview: thumbnails are only inverted after scrolling if night mode is active

### ISSUE THREAD

**Issue by schachmat** [T-Rex96/Easy_xkcd#89]
When opening the app and navigating to the what if overview list for the first time, the first 2 pages or so of thumbnails are not inverted correctly. When scrolling down, cards that are loaded in get a correct inversion filter for the thumbnail. If you scrolled down enough lines so that the first few cards are not loaded anymore you can scroll up again to load them back into the list and then the thumbnails are inverted correctly. Unfortunately I don't know the concept enough to fix the bug myself, but I think an invocation of `comicViewHolder.thumbnail.setColorFilter(themePrefs.getNegativeColorFilter());` is missing for the items loaded in initially. I found this call in `fragments/whatIf/WhatIfOverviewFragment.java` line 203, maybe it should be called before the return in line 187 too?

**Comment by T-Rex96** [comment]
Seems like `onBindViewHolder` isn't always calld when the views are loaded from cache. Moving the call to the `ComicViewHolder` constructor fixed it for me.
