### ISSUE TITLE
ArrayIndexOutOfBoundsException in favorites overview 

### ISSUE THREAD

**Issue by 42SK** [T-Rex96/Easy_xkcd#90]
Whenever I click on one of the lower items in the favorites overview, I get an `ArrayIndexOutOfBoundsException` and the application crashes:
```
E/AndroidRuntime(24006): FATAL EXCEPTION: main
E/AndroidRuntime(24006): Process: de.tap.easy_xkcd, PID: 24006
E/AndroidRuntime(24006): java.lang.ArrayIndexOutOfBoundsException: length=61; index=-38
E/AndroidRuntime(24006): 	at de.tap.easy_xkcd.fragments.overview.OverviewBaseFragment.goToComic(OverviewBaseFragment.java:107)
E/AndroidRuntime(24006): 	at de.tap.easy_xkcd.fragments.overview.OverviewBaseFragment.showComic(OverviewBaseFragment.java:69)
E/AndroidRuntime(24006): 	at de.tap.easy_xkcd.fragments.overview.OverviewRecyclerBaseFragment$CustomOnClickListener.onClick(OverviewRecyclerBaseFragment.java:103)
E/AndroidRuntime(24006): 	at android.view.View.performClick(View.java:5204)
E/AndroidRuntime(24006): 	at android.view.View$PerformClick.run(View.java:21158)

**Comment by T-Rex96** [comment]
They all seem to work for me, how many favorites do you have?

**Comment by 42SK** [comment]
I have about 60 comics marked as favorites.
The first 27 work just fine.

**Comment by T-Rex96** [comment]
Can you try to export your favorites (in the normal favorites screen tap the menu icon and choose favorites export/import) and compare those with the ones shown in overview mode? I'm pretty sure the ones that crash the app won't show up in the exported list.

**Comment by 42SK** [comment]
Indeed, the comics that cause the app to crash are not included in the export file.

**Comment by T-Rex96** [comment]
Excellent, does this version fix the bug? 

[](https://drive.google.com/file/d/0B2jgnOPGw95Bbm1BZlN3THRHY2M/view?usp=sharing)

**Comment by 42SK** [comment]
Yes, that seems to fix it.
Everything works perfectly now.
Thanks a lot!

**Comment by T-Rex96** [comment]
Sweet!
