### ISSUE TITLE
Feature request: Widget Settings

### ISSUE THREAD

**Issue by RussellAult** [T-Rex96/Easy_xkcd#95]
I'm not sure how much work this would be, but it would be great if the widgets had configurable settings. The one I would like to see personally is the option to display the title text below the comic.

Thanks!

-Russ

**Comment by T-Rex96** [comment]
Yeah that's definitely possible. Lately I've been pretty busy with university, so I don't really have time for coding at the moment. I'll add it to my ToDo list though!

**Comment by T-Rex96** [comment]
Okay, so I added two settings: Display Alt Text and Diplay Comic Number. Any other suggestions for widget settings?

**Comment by RussellAult** [comment]
The only other setting I can think of would be Display Comic Title, since the title is often part of the joke too.

**Comment by T-Rex96** [comment]
Right, don't know why anyone would turn that off, but I'll add it
